import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const JSZip = require('../vendor/jszip.min.js');
// Only the two bundled demonstration archives are generated by this command.
const examples = [
  ['welcome', 'Welcome to SideNote', '# A little space for your notes\n\nSideNote brings Markdown notes to your browser sidebar. This website lets you read published SideNote files.\n\n## Open a note\n\nChoose a title on the left. Each page opens a **.snote file**, including its attached images.\n\n- Markdown formatting\n- Code blocks with a copy button\n- Light and dark themes\n- Your images, in the same file\n\n## Get SideNote\n\n[Chrome Web Store](https://chromewebstore.google.com/detail/sidenote/jdgobmepjpcgfcjmocndbbhhigogafak) · [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/sidenote1/) · [Source code](https://github.com/IHaBiS02/SideNote)\n\n> This is a published example note. Replace it with one exported from SideNote.\n'],
  ['publishing', 'Publish your own notes', '# Write in SideNote. Publish here.\n\n1. Write your note in SideNote.\n2. Export the note as **.snote**.\n3. Put the file in the website’s `notes/` folder.\n4. Add it to `notes/index.json`.\n5. Push the gh-pages branch.\n\n```json\n{ "id": "my-note", "title": "My note", "file": "notes/my-note.snote" }\n```\n\nThe list follows the order of `notes/index.json`. The title inside the archive is shown when the note opens.\n\n## A formatting sample\n\n| Feature | Included |\n| --- | --- |\n| Headings and lists | Yes |\n| Attached images | Yes |\n| Code copy button | Yes |\n\n- [x] Write a note\n- [ ] Publish your next idea\n\n## Attached image\n\n![SideNote icon](images/example.png)\n\nOnly files you publish in this repository are available to visitors. Your private notes in the extension stay on your device.\n'],
];
for (const [id, title, content] of examples) {
  const zip = new JSZip();
  const options = { date: new Date('2026-01-01T00:00:00Z') };
  zip.file('metadata.json', JSON.stringify({ title, settings: { fontSize: 14, lineHeight: 1.5, codeLineHeight: 1.2 } }), options);
  zip.file('note.md', content, options);
  if (id === 'publishing') {
    const { readFile } = await import('node:fs/promises');
    zip.file('images/example.png', await readFile(new URL('../assets/icon128.png', import.meta.url)), options);
  }
  await writeFile(new URL(`../notes/${id}.snote`, import.meta.url), await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' }));
}
